on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-roadmap-placeholder:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Deploy Placeholder to EC2 via Rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: /public/
          remote_path: /var/www/placeholder-site/
          remote_host: ${{ secrets.EC2_IP }}
          remote_user: ec2-user
          remote_key: ${{ secrets.EC2_SSH_KEY }}
  deploy-ansible:
    if: false
    name: Deploy to AWS via Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run the playbook
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          cd nodejs-aws-deployment/ansible

          echo "[webserver]" > pipeline_inventory.ini
          echo "$EC2_HOST ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519" >> pipeline_inventory.ini

